# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='course_id',
        ),
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
